AWSTemplateFormatVersion: '2010-09-09'
Description: Procure a t3.micro EC2

# Defining parameters to be referenced
Parameters:
  CurrentSecurityGroupId:
    Type: String
    Description: Security Group ID passed from Github Secrets
  PostgresPassword:
    Type: String
    NoEcho: true # This hides the password in AWS logs

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-019715e0d74f695be  # AMI image of Ubuntu 24.04
      KeyName: login                  # Existing .pem file name
      SecurityGroupIds:
        - !Ref CurrentSecurityGroupId        # From Github secrets
      Tags:
        - Key: Name
          Value: Project-Server-Develop   # Name of EC2
      
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # The -e flag makes the script STOP if any command fails
          # The -x flag prints every command to the logs for easier debugging
          # 1. Update the system
          apt-get update -y
          apt-get upgrade -y

          # 2. Install postgresql and its utilities
          apt-get install -y postgresql postgresql-contrib

          # 3. Start and enable the service
          systemctl start postgresql
          systemctl enable postgresql

          # 4. We set a password for the 'postgres' user
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${PostgresPassword}';"

          # 5. Create database
          sudo -u postgres psql -c "CREATE DATABASE my_project_db;"

          # 6. Configure remote access
          echo "listen_addresses = '*'" >> /etc/postgresql/16/main/postgresql.conf
          echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/16/main/pg_hba.conf

          systemctl restart postgresql