AWSTemplatFormatVersion: '2010-09-09'
Description: S3 Bucket for User Photos

Resources:
  UserProfileBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Globally unique bucket name
      BucketName: "ayush-project-photos"
      # Bucket is kept private for security
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true