name: Infrastructure Procurement

on:
  push:
    branches: [ develop ]
  workflow_dispatch:			# Lets us click "Run workflow" manually

jobs:
  DeployEC2:
    runs-on: ubuntu-latest
    permissions:
      id-token: write		# Required for secure login in AWS
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Using the ARN of the new role
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1 # Mumbai Region

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Dev-Stack
          template: ./infrastructure/Ec2.yml
          # To avoid error when there is no update/change in file
          no-fail-on-empty-changeset: "1"
          # We pass the Security Group ID here
          parameter-overrides: >-
            CurrentSecurityGroupId=${{ secrets.SecurityGroupId }},
            PostgresPassword=${{ secrets.DB_PASSWORD }}

  DeployS3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1
      - name: Deploy S3 Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: S3-Storage-Stack
          template: ./infrastructure/S3.yml
          no-fail-on-empty-changeset: "1"

  DeploySES:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1
      - name: Deploy SES Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: SES-Email-Stack # Separate Stack Name
          template: ./infrastructure/Ses.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "ProjectEmail=${{ secrets.PROJECT_EMAIL }}"

  DeployECR:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1
      - name: Deploy ECR Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ECR-Repo-Stack
          template: ./infrastructure/Ecr.yml
          no-fail-on-empty-changeset: "1"